Fix startup error introduced in dd0169b068d69b3b01c133eadd2288b256a43c75
uncaughtException TypeError:
module$electron$utils.safe_decode_uri_component is not a function

Interesting that kondo doesn't catch invalid fns from js requires